blog/urls.py
from django.urls import path

from blog import views
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog-list'),
    path('create/', views.BlogCreateView.as_view(), name='blog-create'),
    path('<int:pk>/', views.BlogDetailView.as_view(), name='blog-detail'),
    path('blog/<int:pk>/update/', views.BlogUpdateView.as_view(), name='blog-update'),
    path('blog/<int:pk>/delete/', views.BlogDeleteView.as_view(), name='blog-delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('email_campaign.urls', namespace='email_campaign',)),
    path('users/', include('users.urls', namespace='users',)),
    path('users/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls', namespace='blog',)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, ConfirmationSentView, EmailConfirmedView, \
    EmailConfirmationFailedView, ProfileView, ConfirmEmailView

app_name = UsersConfig.name
urlpatterns = [
    # Main Url
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    # Log Out Url
    path('logout/', LogoutView.as_view(), name='logout'),

    # Registration Url
    path('register/', RegisterView.as_view(template_name='users/register.html'), name='register'),

    # Email Confirmation Urls
    path('email_confirmation_sent/', ConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm_email/<str:uidb64>/<str:token>/', ConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('email_confirmation_failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),

    # Profile Url
    path('profile/', ProfileView.as_view(), name='profile'),

    # Password Reset Urls
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/reset_password/password_reset.html',
             success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/reset_password/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/reset_password/password_reset_confirm.html',
             success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/reset_password/password_reset_complete.html'),
         name='password_reset_complete'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Email')

    first_name = models.CharField(max_length=35, verbose_name='First Name')
    last_name = models.CharField(max_length=35, verbose_name='Last Name', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='Phone', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Avatar', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
# Description: Views for users app
import random
import string

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from config import settings
from django import forms

from django.views.generic import CreateView, UpdateView
from django.views import View

from django.core.mail import send_mail

from django.shortcuts import redirect, reverse, render

from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import login
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView as BaseLoginView, PasswordResetDoneView
from django.contrib.auth.views import LogoutView as BaseLogoutView

from users.forms import UserProfileForm, UserRegisterForm
from users.models import User


class LoginView(BaseLoginView):
    """Login on website"""
    title = 'Login'
    template_name = 'users/login.html'
    success_url = reverse_lazy('email_campaign:index')


class LogoutView(BaseLogoutView):
    """Logout from website"""
    template_name = 'users/login.html'
    success_url = reverse_lazy('email_campaign:index')


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')
    title = 'New user registration'

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        user.save()
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('users:confirm_email', kwargs={'uidb64': uid, 'token': token})
        current_site = get_current_site(self.request)

        send_mail(
            recipient_list=[user.email],
            subject='Registration on the site',
            message=f'You have successfully registered on the website, please activate your account by clicking on the '
                    f'link: http://{current_site}{activation_url}"',
            from_email=settings.EMAIL_HOST_USER
        )

        return redirect('users:email_confirmation_sent')


class ConfirmationSentView(PasswordResetDoneView):
    """User confirmation sent"""
    template_name = "users/includes/inc_email_confirmation_sent.html"


class ConfirmEmailView(View):
    """Confirm user email"""

    def get(self, request, *args, **kwargs):
        try:
            uid = urlsafe_base64_decode(kwargs['uidb64']).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, kwargs['token']):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('users:email_confirmed')
        else:
            return redirect('users:email_confirmation_failed')


class EmailConfirmedView(TemplateView):
    """Email confirmation success"""
    template_name = 'users/includes/inc_email_confirmed.html'
    title = "Your email is activated."


class EmailConfirmationFailedView(TemplateView):
    """Email confirmation failed"""
    template_name = 'users/includes/inc_email_confirmation_failed.html'
    title = "Email confirmation failed"


@method_decorator(login_required, name='dispatch')
class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('email_campaign:index')
    template_name = 'users/profile.html'

    def get_object(self, queryset=None):
        return self.request.user


# def password_reset(request):
#     if request.method == 'POST':
#         email = request.POST.get('email')
#         password1 = request.POST.get('password1')
#         password2 = request.POST.get('password2')
#         try:
#             user = User.objects.get(email=email)
#             characters = string.ascii_letters + string.digits
#             new_password = ''.join([str(random.choice(characters)) for _ in range(12)])
#             user.set_password(new_password)
#             user.save()
#
#             send_mail(
#                 subject="You've changed your password",
#                 message=f'You have successfully changed your password, your new password: {new_password}',
#                 from_email=settings.EMAIL_HOST_USER,
#                 recipient_list=[email]
#             )
#             return redirect(reverse("users:login"))  # redirect to login page
#         except User.DoesNotExist:
#             return render(request, 'users/includes/inc_password_reset.html',
#                           {'error_message': 'User not found'})  # error message if user not found
#     return render(request, 'users/includes/inc_password_reset.html')

users/templates/users/login.html
{% extends 'email_campaign/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container" align="center">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Sign In
                </h3>
            </div>
            <form method="post" enctype="multipart/form-data">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">Log In</button>
                    <a href="{% url 'users:password_reset' %}" class="btn btn-link">Forgot Password?</a>
                </div>
                <div class="card-footer py-4">
                    Don't have an account?&nbsp;
                    <a href="{% url 'users:register' %}">Sign Up</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'email_campaign/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="col-12">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Profile
                        </h3>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form|crispy}}
                            <button type="submit" class="btn btn-primary">Save Changes</button>
                        </div>
                        <div class="card-footer py-4">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'email_campaign/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container" align="center">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Register
                </h3>
            </div>
            <form method="post" enctype="multipart/form-data">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">Sign Up</button>
                </div>
                <div class="card-footer py-4">
                   <small class="text-muted">Already have an account?</small>&nbsp;
                    <a href="{% url 'users:login' %}">Sign In</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}