blog/urls.py
from django.urls import path

from blog import views
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog-list'),
    path('create/', views.BlogCreateView.as_view(), name='blog-create'),
    path('<int:pk>/', views.BlogDetailView.as_view(), name='blog-detail'),
    path('blog/<int:pk>/update/', views.BlogUpdateView.as_view(), name='blog-update'),
    path('blog/<int:pk>/delete/', views.BlogDeleteView.as_view(), name='blog-delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('email_campaign.urls', namespace='email_campaign',)),
    path('users/', include('users.urls', namespace='users',)),
    path('users/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls', namespace='blog',)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

email_campaign/urls.py
from django.urls import path

from email_campaign.apps import EmailCampaignConfig
import email_campaign.views as views

app_name = EmailCampaignConfig.name

urlpatterns = [
    path('', views.index, name='index'),
    path('campaign/contacts/', views.contacts, name='contacts'),
    path('campaign/', views.CampaignListView.as_view(), name='campaign-list'),
    path('campaign/create/', views.CampaignCreateView.as_view(), name='campaign-create'),
    path('campaign/<int:pk>/detail/', views.CampaignDetailView.as_view(), name='campaign-detail'),
    path('campaign/<int:pk>/update/', views.CampaignUpdateView.as_view(), name='campaign-update'),
    path('campaign/<int:pk>/delete/', views.CampaignDeleteView.as_view(), name='campaign-delete'),
    path('client/', views.ClientListView.as_view(), name='client-list'),
    path('client/crete/', views.ClientCreateView.as_view(), name='client-create'),
    path('client/<int:pk>/detail/', views.ClientDetailView.as_view(), name='client-detail'),
    path('client/<int:pk>/update/', views.ClientUpdateView.as_view(), name='client-update'),
    path('client/<int:pk>/delete/', views.ClientDeleteView.as_view(), name='client-delete'),

]

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, ConfirmationSentView, EmailConfirmedView, \
    EmailConfirmationFailedView, ProfileView, ConfirmEmailView

app_name = UsersConfig.name
urlpatterns = [
    # Main Url
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    # Log Out Url
    path('logout/', LogoutView.as_view(), name='logout'),

    # Registration Url
    path('register/', RegisterView.as_view(template_name='users/register.html'), name='register'),

    # Email Confirmation Urls
    path('email_confirmation_sent/', ConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm_email/<str:uidb64>/<str:token>/', ConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('email_confirmation_failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),

    # Profile Url
    path('profile/', ProfileView.as_view(), name='profile'),

    # Password Reset Urls
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/reset_password/password_reset.html',
             success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/reset_password/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/reset_password/password_reset_confirm.html',
             success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/reset_password/password_reset_complete.html'),
         name='password_reset_complete'),

]

email_campaign/models.py
from datetime import datetime, timedelta
from django.utils import timezone

from django.db import models
from config import settings

NULLABLE = {'null': True, 'blank': True}


class Client(models.Model):
    """Client model"""
    client_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Client owner',
                                     **NULLABLE, )
    email = models.EmailField(max_length=150, unique=True, **NULLABLE, verbose_name='Email', )
    first_name = models.CharField(max_length=100, verbose_name='First Name', **NULLABLE, )
    last_name = models.CharField(max_length=100, verbose_name='Last Name', **NULLABLE, )
    comment = models.TextField(**NULLABLE, verbose_name='Comment', )

    def __str__(self):
        return f"{self.email} ({self.first_name} {self.last_name})"

    class Meta:
        verbose_name = 'Client'
        verbose_name_plural = 'Clients'


class MailingPeriod(models.IntegerChoices):
    DAY = 1, 'Daily'
    WEEK = 2, 'Weekly'
    MONTH = 3, 'Monthly'

    def __str__(self) -> str:
        return self.label


class MailingStatus(models.IntegerChoices):
    FINISHED = 1, 'Finished'
    CREATED = 2, 'Created'
    RUNS = 3, 'Runs'

    def __str__(self) -> str:
        return self.label


class MailingCampaign(models.Model):
    """Campaign model"""
    send_time = models.TimeField(verbose_name='Send time', )
    period = models.SmallIntegerField(choices=MailingPeriod.choices, verbose_name='Frequency', **NULLABLE, )
    mail_status = models.SmallIntegerField(choices=MailingStatus.choices, verbose_name='Status',
                                           default=MailingStatus.CREATED)
    next_time_run = models.DateTimeField(verbose_name='Next time run', null=True, default=None, )
    mail_clients = models.ManyToManyField(Client, verbose_name='Clients', )
    mail_subject = models.CharField(max_length=100, verbose_name='Subject', **NULLABLE, )
    body = models.TextField(verbose_name='Body', **NULLABLE)
    mail_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Campaign owner', )

    def __str__(self):
        return f"{self.mail_subject} в {self.send_time} ({self.period}"

    def get_next_time_run(self) -> datetime:
        """Return next time run"""
        now = timezone.now()
        if self.send_time >= now.time():
            # if time of start is 10:00 and now is 09:00
            # we will send email today
            next_datetime = now.today()
        else:
            match self.period:
                case MailingPeriod.DAY:
                    next_datetime = now.today() + timedelta(days=1)
                case MailingPeriod.WEEK:
                    next_datetime = now.today() + timedelta(days=7)
                case MailingPeriod.MONTH:
                    next_datetime = now.today() + timedelta(days=30)
                case _:
                    raise ValueError('Unknown period')

        return datetime.combine(next_datetime.date(), self.send_time)

    def save(self, *args, **kwargs):
        if self.pk:  # if we are updating object
            cls = self.__class__
            old_object = cls.objects.get(pk=self.pk)
            if old_object.send_time == self.send_time and old_object.period == self.period:
                # if time and period not changed we are not changing next_time_run
                return

        # if we are creating object or time or period changed
        self.next_time_run = self.get_next_time_run()

        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Campaign'
        verbose_name_plural = 'Campaigns'


class Log(models.Model):
    """Log model"""

    STATUS_SUCCESSFUL = 'SUCCESS'
    STATUS_FAILED = 'FAILED'

    STATUS_CHOICES = (
        (STATUS_SUCCESSFUL, 'Success'),
        (STATUS_FAILED, 'Failed'),
    )

    log_created_at = models.DateTimeField(auto_now_add=True, verbose_name='Creation Time', **NULLABLE, )
    log_status = models.CharField(max_length=50, choices=STATUS_CHOICES, verbose_name='Status', **NULLABLE)
    log_client = models.ForeignKey(Client, on_delete=models.SET_NULL, verbose_name='Client', **NULLABLE, )
    log_mailing = models.ForeignKey(MailingCampaign, on_delete=models.CASCADE, verbose_name='Mailing', **NULLABLE, )
    log_server_response = models.TextField(**NULLABLE, verbose_name='Server response', )

    def __str__(self):
        return f"{self.log_client} - {self.log_status}"

    class Meta:
        verbose_name = 'Log'
        verbose_name_plural = 'Logs'

email_campaign/forms.py
from django import forms

from email_campaign.models import MailingCampaign, Client


class MailingCampaignForm(forms.ModelForm):
    class Meta:
        model = MailingCampaign
        exclude = ('mail_owner', 'next_time_run', 'mail_status',)


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('client_owner',)

email_campaign/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator

from users.models import User
from .models import MailingCampaign, Log, Client

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from email_campaign.forms import MailingCampaignForm, ClientForm


def index(request):
    return render(request, 'email_campaign/index.html')


@method_decorator(login_required, name='dispatch')
class CampaignListView(ListView, LoginRequiredMixin):
    model = MailingCampaign
    template_name = 'email_campaign/campaign_list.html'

    def get_context_data(self, **kwargs):
        context = super(CampaignListView, self).get_context_data(**kwargs)
        context['title'] = 'Mailing Campaigns'
        return context

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser or user.is_staff:
            queryset = super().get_queryset()
        else:
            queryset = super().get_queryset().filter(
                mail_owner=user.pk
            )
        return queryset


class CampaignCreateView(LoginRequiredMixin, CreateView):
    model = MailingCampaign
    form_class = MailingCampaignForm
    template_name = 'email_campaign/campaign_form.html'

    def get_context_data(self, **kwargs):
        context = super(CampaignCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Mailing Campaign Creation'
        return context

    def get_success_url(self):
        return reverse('email_campaign:campaign-detail', args=[self.object.pk])

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.mail_owner = self.request.user
        self.object.save()
        return redirect(self.get_success_url())


class CampaignUpdateView(LoginRequiredMixin, UpdateView):
    model = MailingCampaign
    form_class = MailingCampaignForm
    template_name = 'email_campaign/campaign_form.html'

    def get_context_data(self, **kwargs):
        context = super(CampaignUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Edit Campaign'
        return context

    def get_success_url(self):
        return reverse('email_campaign:campaign-detail', args=[self.object.pk])


class CampaignDeleteView(LoginRequiredMixin, DeleteView):
    model = MailingCampaign
    template_name = 'email_campaign/campaign_confirm_delete.html'
    success_url = reverse_lazy('email_campaign:campaign-list')

    def get_context_data(self, **kwargs):
        context = super(CampaignDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Delete Campaign'
        return context


class CampaignDetailView(DetailView, LoginRequiredMixin):
    model = MailingCampaign
    template_name = 'email_campaign/campaign_detail.html'

    def get_context_data(self, **kwargs):
        context = super(CampaignDetailView, self).get_context_data(**kwargs)
        context['title'] = 'Campaign Details'
        return context


@method_decorator(login_required, name='dispatch')
class ClientListView(ListView, LoginRequiredMixin):
    model = Client
    template_name = 'email_campaign/client_list.html'

    def get_context_data(self, **kwargs):
        context = super(ClientListView, self).get_context_data(**kwargs)
        context['title'] = 'Clients'
        return context

    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            if user.is_superuser or user.is_staff:
                queryset = super().get_queryset()
            else:
                queryset = super().get_queryset().filter(
                    client_owner=user.pk
                )
        else:
            queryset = super().get_queryset().filter(
                pk=None
            )
        return queryset


class ClientCreateView(CreateView, LoginRequiredMixin):
    model = Client
    form_class = ClientForm
    template_name = 'email_campaign/client_form.html'

    def get_context_data(self, **kwargs):
        context = super(ClientCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Clients Creation'
        return context

    def get_success_url(self):
        return reverse('email_campaign:client-detail', args=[self.object.pk])

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.client_owner = self.request.user
        self.object.save()
        return redirect(self.get_success_url())


class ClientUpdateView(UpdateView, LoginRequiredMixin):
    model = Client
    form_class = ClientForm
    template_name = 'email_campaign/client_form.html'

    def get_context_data(self, **kwargs):
        context = super(ClientUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Edit Clients'
        return context

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.client_owner != self.request.user and not self.request.user.is_staff:
            raise Http404
        return self.object


class ClientDetailView(DetailView, LoginRequiredMixin):
    model = Client
    template_name = 'email_campaign/client_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ClientDetailView, self).get_context_data(**kwargs)
        context['title'] = 'Clients Details'
        return context


class ClientDeleteView(DeleteView, LoginRequiredMixin):
    model = Client
    template_name = 'email_campaign/client_confirm_delete.html'
    success_url = reverse_lazy('email_campaign:client-list')

    def get_context_data(self, **kwargs):
        context = super(ClientDeleteView, self).get_context_data()
        context['title'] = 'Delete Client'
        return context


def contacts(requests):

    if requests.method == 'POST':
        name = requests.POST.get('name')
        email = requests.POST.get('email')
        subject = requests.POST.get('subject')
        message = requests.POST.get('message')

    context = {
        'title': 'Contact Us',
    }

    return render(requests, 'email_campaign/contacts.html', context)

email_campaign/templates/email_campaign/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/product.css' %}" rel="stylesheet">
</head>

<body>

<nav class="site-header sticky-top py-1">
    <div class="container d-flex flex-column flex-md-row justify-content-between">
        <a class="py-2" href="{% url 'email_campaign:index' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                 class="d-block mx-auto">
                <circle cx="12" cy="12" r="10"></circle>
                <line x1="14.31" y1="8" x2="20.05" y2="17.94"></line>
                <line x1="9.69" y1="8" x2="21.17" y2="8"></line>
                <line x1="7.38" y1="12" x2="13.12" y2="2.06"></line>
                <line x1="9.69" y1="16" x2="3.95" y2="6.06"></line>
                <line x1="14.31" y1="16" x2="2.83" y2="16"></line>
                <line x1="16.62" y1="12" x2="10.88" y2="21.94"></line>
            </svg>
        </a>

        <a class="py-2 d-none d-md-inline-block" href="{% url 'email_campaign:index' %}">Home</a>
        <a class="py-2 d-none d-md-inline-block" href="{% url 'email_campaign:campaign-list' %}">Campaign</a>
        <a class="py-2 d-none d-md-inline-block" href="{% url 'email_campaign:client-list' %}">Clients</a>
        <a class="py-2 d-none d-md-inline-block" href="{% url 'email_campaign:contacts' %}">Contacts</a>
        <a class="py-2 d-none d-md-inline-block" href="{% url 'blog:blog-list' %}">Blog</a>
        {% if user.is_authenticated %}
        <a class="py-2 d-none d-md-inline-block" href="{% url 'users:profile' %}">Profile</a>
        <a class="py-2 d-none d-md-inline-block" href="{% url 'users:logout' %}">Log Out</a>
        {% else %}
        <a class="py-2 d-none d-md-inline-block" href="{% url 'users:login' %}">Sign In</a>
        <a class="py-2 d-none d-md-inline-block" href="{% url 'users:register' %}">Sign Up</a>
        {% endif %}
    </div>
</nav>

<main role="main">
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
            <p class="lead text-muted">{{ description }}</p>
            <p>
            </p>
        </div>

        <!-- Album content -->
        <div class="album py-5">
            <div class="container">
                <div class="row">
                    <!-- Catalog content -->
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </section>
</main>

{% include 'email_campaign/includes/inc_footer.html' %}

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>

</body>
</html>

email_campaign/templates/email_campaign/campaign_confirm_delete.html
{% extends 'email_campaign/base.html' %}
{% load static %}

{% block content %}
    <div class="col-12" align="center">
        <div class="rom ">
            <div class="col-6">
                <div class="card no-hover">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Are you sure you want to delete this Product: {{ object.title|title }}</p>
                            <button type="submit" class="btn btn-danger">Confirm Delete</button>
                            <a href="{% url 'email_campaign:campaign-detail' object.pk  %}" class="btn btn-warning">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

email_campaign/templates/email_campaign/campaign_detail.html
{% extends 'email_campaign/base.html' %}

{% block content %}
<style>
    .email-table {
        width: 100%;
        border-collapse: collapse;
    }

    .email-table th, .email-table td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    .email-table th {
        background-color: #f2f2f2;
    }

    .email-table tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    .email-table tr:hover {
        background-color: #ddd;
    }

    .subscribers-list {
        list-style-type: none;
        padding: 0;
    }

    .subscribers-list li {
        margin-bottom: 4px;
    }

    .button-container {
        margin-top: 10px;
        text-align: right;
    }

    .button-container a {
        text-decoration: none;
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border-radius: 5px;
        margin-right: 10px;
        display: inline-block;
    }

    .button-container a:hover {
        background-color: #0056b3;
    }
</style>

<table class="email-table">
    <thead>
        <tr>
            <th>Email Subject</th>
            <th>Message</th>
            <th>Time</th>
            <th>Periodicity</th>
            <th>Status</th>
            <th>Subscribers</th>
            <th>Owner</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ object.mail_subject }}</td>
            <td>{{ object.body }}</td>
            <td>{{ object.send_time }}</td>
            {% if object.period == 1 %}
            <td>Daily</td>
            {% elif object.period == 2 %}
            <td>Weekly</td>
            {% else %}
            <td>Monthly</td>
            {% endif %}
            <td>{{ object.get_mail_status_display }}</td>
            <td>
                <ul class="subscribers-list">
                    {% for client in object.mail_clients.all %}
                        <li>{{ client.email }}</li>
                    {% endfor %}
                </ul>
            </td>
            <td>{{ object.mail_owner }}</td>
        </tr>
    </tbody>
</table>
<div class="button-container">
    <a href="{% url 'email_campaign:campaign-delete' object.pk %}">Delete</a>
    <a href="{% url 'email_campaign:campaign-update' object.pk %}">Edit</a>
    <a href="{% url 'email_campaign:campaign-list' %}">Back to Campaign</a>
</div>
{% endblock %}

email_campaign/templates/email_campaign/campaign_list.html
{% extends 'email_campaign/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <a class="btn btn-primary create-campaign-button" href="{% url 'email_campaign:campaign-create' %}">Create
                Campaign</a>
        </div>
    </div>
    <div class="row mt-4">
        {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-3 custom-card">
                <div class="card-body">
                    <h4 class="card-title">{{ object.mail_subject }}</h4>
                    <hr class="divider">
                    {% if object.period == 1%}
                    <p class="card-text"><strong>Periodicity:</strong> Daily</p>
                    {% elif object.period == 2%}
                    <p class="card-text"><strong>Periodicity:</strong> Weekly</p>
                    {% elif object.period == 3%}
                    <p class="card-text"><strong>Periodicity:</strong> Monthly</p>
                    {% endif %}
                    <p class="card-text"><strong>Send Time:</strong> {{ object.send_time }}</p>
                    <p class="card-text"><strong>Owner:</strong> {{ object.mail_owner }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-outline-primary btn-sm"
                               href="{% url 'email_campaign:campaign-detail' object.pk %}">Details</a>
                        </div>
                        {% if object.mail_status == 1 %}
                        <small class="text-secondary">Finished</small>
                        {% elif object.mail_status == 2 %}
                        <small class="text-success">Created</small>
                        {% elif object.mail_status == 3 %}
                        <small class="text-danger">Running</small>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<style>
    .card-container {
        display: flex;
        justify-content: space-between; /* Adjust as needed */
    }

    .card {
        width: 100%;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        transition: transform 0.2s; /* Add transition for the hover effect */
    }

    /* Apply the hover effect */
    .card:hover {
        transform: translateY(-5px);
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
    }

    .card-title {
        font-size: 1.25rem;
        margin-bottom: 10px;
    }

    .card-text {
        font-size: 0.875rem;
        margin-bottom: 5px;
    }

    .btn-group {
        margin-top: 10px;
    }
</style>
{% endblock %}

email_campaign/templates/email_campaign/client_detail.html
{% extends 'email_campaign/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .email-table {
        width: 100%;
        border-collapse: collapse;
    }

    .email-table th, .email-table td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    .email-table th {
        background-color: #f2f2f2;
    }

    .email-table tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    .email-table tr:hover {
        background-color: #ddd;
    }

    .subscribers-list {
        list-style-type: none;
        padding: 0;
    }

    .subscribers-list li {
        margin-bottom: 4px;
    }

    .button-container {
        margin-top: 10px;
        text-align: right;
    }

    .button-container a {
        text-decoration: none;
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border-radius: 5px;
        margin-right: 10px;
        display: inline-block;
    }

    .button-container a:hover {
        background-color: #0056b3;
    }
</style>

<table class="email-table">
    <thead>
        <tr>
            <th>Email Subject</th>
            <th>Message</th>
            <th>Time</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ object.email }}</td>
            <td>{{ object.first_name}}</td>
            <td>{{ object.last_name }}</td>
        </tr>
    </tbody>
</table>
<div class="button-container">
    <a href="{% url 'email_campaign:client-delete' object.pk %}">Delete</a>
    <a href="{% url 'email_campaign:client-update' object.pk %}">Edit</a>
    <a href="{% url 'email_campaign:client-list' %}">Back to Clients</a>
</div>
{% endblock %}

email_campaign/templates/email_campaign/client_list.html
{% extends 'email_campaign/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <a href="{% url 'email_campaign:client-create' %}" class="btn btn-primary create-client-button">Add Client</a>
        </div>
    </div>

    <div class="row mt-4">
        {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-3 custom-card">
                <div class="card-body">
                    <h4 class="card-title">{{ object.email }}</h4>
                    <hr class="divider">
                    <p class="card-text"><strong>First Name:</strong> {{ object.first_name }}</p>
                    <p class="card-text"><strong>Last Name:</strong> {{ object.last_name }}</p>
                    <p class="card-text"><strong>Owner:</strong> {{ object.client_owner }}</p>
                    <p class="card-text"><strong>Comment:</strong> {{ object.comment }}</p>
                </div>
                <div class="card-footer bg-transparent border-top-0">
                    <div class="d-flex justify-content-between align-items-center">
                        <a href="{% url 'email_campaign:client-detail' object.pk %}" class="btn btn-outline-primary btn-sm">Details</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<style>

    .create-client-button {
        margin-top: 20px;
    }

    .custom-card {
        border: 1px solid #e0e0e0;
        border-radius: 10px;
        transition: transform 0.2s;
    }

    .custom-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    }

    .divider {
        margin-top: 10px;
        margin-bottom: 10px;
        border: none;
        height: 1px;
        background-color: #e0e0e0;
    }

    .card-title {
        font-size: 1.5rem;
        color: #333;
    }

    .card-text {
        color: #555;
    }

    .btn-outline-primary {
        color: #007bff;
        border-color: #007bff;
    }
</style>

{% endblock %}

email_campaign/templates/email_campaign/index.html
{% extends 'email_campaign/base.html' %}